version: "3.8"

services:
  steamstorage.api:
    image: steamstorage.api
    env_file:
      - env/api.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "8082:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: SteamStorageAPI/Dockerfile
  
  loginwebapp:
    image: loginwebapp
    env_file:
      - env/loginwebapp.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8083:80"
      - "8084:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: LoginWebApp/Dockerfile